version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~/opt/data:/data/db   # persist Mongo data on host
    networks:
      - tier-network

  backend:
    build: ./backend   # path to your backend Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    networks:
      - tier-network

  frontend:
    build: ./frontend   # path to your frontend Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - tier-network

networks:
  tier-network:
    driver: bridge
