version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      -  /home/ubuntu/opt/data:/data/db # persist Mongo data on host
    networks:
      - tier-network

  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    networks:
      - tier-network

  frontend:
    image: ${FRONTEND_IMAGE}   # path to your frontend Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - tier-network

networks:
  tier-network:
    driver: bridge
